services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASS: "${POSTGRES_PASS}"
      POSTGRES_DB: "${POSTGRES_DB}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    command: ["migrate"]
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build: .
    command: ["server"]
    env_file: .env
    ports:
      - "${API_PORT}:7777"
    depends_on:
      - migrations

volumes:
  postgres-data:
